---
name: On Push

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  rust_tests:
    name: Rust Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: asdf-vm/actions/install@v3
      - name: Execute tests
        run: |
          cd rust
          cargo test
